kind: Service
apiVersion: v1alpha1
metadata:
  labels:
    name: redis
  name: redis
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: 32379
  selector:
    name: redis
