apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # metadata.name的内容是由"复数名.分组名"构成，如下，equivalentnodes是复数名，keepedge.k8s.io是分组名
  name: equalnodes.keepedge.io
spec:
  # 分组名，在REST API中也会用到的，格式是: /apis/分组名/CRD版本
  group: keepedge.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # 是否有效的开关.
      served: true
      # 只有一个版本能被标注为storage
      storage: true
  # 范围是属于namespace的
  scope: Namespaced
  names:
    # 复数名
    plural: equalnodes
    # 单数名
    singular: equalnode
    # 类型名
    kind: Equalnode
    # 简称，就像service的简称是svc
    shortNames:
    - eqnd
  go get -u k8s.io/apimachinery/pkg/apis/meta/v1 \
  && go get -u k8s.io/code-generator/... \
  && cd $GOPATH/src/k8s.io/code-generator \
  && ./generate-groups.sh all \
  keepedge/pkg/client \
  keepedge/pkg/apis \
  keepedge:v1