apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # metadata.name的内容是由"复数名.分组名"构成，如下，equivalentnodes是复数名，keepedge.k8s.io是分组名
  name: tenants.keepedge.io
spec:
  # 分组名，在REST API中也会用到的，格式是: /apis/分组名/CRD版本
  group: keepedge.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # 是否有效的开关.
      served: true
      # 只有一个版本能被标注为storage
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                tenant_id:
                  type: string
                status:
                  type: string
                message:
                  type: string

  # 范围是属于namespace的
  scope: Namespaced
  names:
    # 复数名
    plural: tenants
    # 单数名
    singular: tenant
    # 类型名
    kind: Tenant
    # 简称，就像service的简称是svc
    shortNames:
      - tenant

