apiVersion: v1alpha1
kind: Service
metadata:
  name: admission-webhook-example
  namespace: default
  labels:
    app: admission-webhook-example
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: admission-webhook-example

