database:
  drivername: ""
  aliasname: ""
  datasource: /var/lib/keepedge/keep.db
modules:
  healthzagent:
    enable: true
    hostinfostat: null
    cpu: null
    cpuusage: 0
    mem: null
    diskpartitionstat: null
    diskiocountersstat: null
    netiocountersstat: null
    defaultedgehealthinterval: 30
    devicemqtttopics:
    - clock_sensor
  logsagent:
    enable: true
    loglevel: 6
    logtime: 2021-12-27T11:01:57.40508683+08:00
    logfilename: ""
    loginfo: ""
    logfiles:
    - /var/log/keepedge/keep_edgeagent_logs.log
  edgepublisher:
    enable: true
    httpserver: http://192.168.1.128
    port: 20000
    serveport: 20350
    heartbeat: 15
    edgemsgqueens:
    - keep_log_topic
    - keep_data_topic
    tlscafile: ""
    tlscertfile: ""
    tlsprivatekeyfile: ""
    beehivetimeout: 500ms
    hostnameoverride: edge03-zlj
    localip: 192.168.1.128
    token: ""
  edgetwin:
    enable: true
    sqlitefilepath: /var/lib/keepedge/edgeagent.db
    beehivetimeout: 500ms
  devicemapperinterface:
    enable: true
