apiVersion: v1alpha1
kind: ConfigMap
metadata:
  name: redis-conf
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    requirepass 1qaz2wsx.
    pidfile .pid
    appendonly yes
    cluster-config-file nodes-6379.conf
    pidfile /data/k8s/mnt/redis/log/redis-6379.pid
    cluster-config-file /data/k8s/mnt/redis/conf/redis.conf
    dir /data/k8s/mnt/redis/data/
    logfile "/data/k8s/mnt/redis/log/redis-6379.log"
    cluster-node-timeout 5000
    protected-mode no
