kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
#  namespace: default
  name: pod-reader
rules:
  - apiGroups: [""] # "" 表明访问的api组是core
    resources: ["pods"]
    verbs: ["get", "watch", "list"]